create table activity_types
(
    is_active   boolean,
    created_at  timestamp(6) not null,
    created_by  bigint,
    id          bigint generated by default as identity
        primary key,
    updated_at  timestamp(6),
    updated_by  bigint,
    description varchar(255),
    name        varchar(255)
);


create table lead_sources
(
    created_at timestamp(6) not null,
    created_by bigint,
    id         bigint generated by default as identity
        primary key,
    updated_at timestamp(6),
    updated_by bigint,
    name       varchar(255)
);

alter table lead_sources
    owner to postgres;

create table roles
(
    created_at  timestamp(6) not null,
    created_by  bigint,
    id          bigint generated by default as identity
        primary key,
    updated_at  timestamp(6),
    updated_by  bigint,
    description varchar(255),
    name        varchar(255)
);


create table users
(
    created_at    timestamp(6) not null,
    created_by    bigint,
    id            bigint generated by default as identity
        primary key,
    role_id       bigint       not null
        constraint fkp56c1712k691lhsyewcssf40f
            references roles,
    updated_at    timestamp(6),
    updated_by    bigint,
    email         varchar(255) not null
        unique,
    first_name    varchar(255) not null,
    last_name     varchar(255) not null,
    password_hash varchar(255) not null,
    status        varchar(255) not null
        constraint users_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying, 'PENDING'::character varying, 'SUSPENDED'::character varying, 'DELETED'::character varying])::text[])),
    username      varchar(255) not null
        unique
);


create table audit_trails
(
    created_at  timestamp(6) not null,
    created_by  bigint,
    entity_id   bigint       not null,
    id          bigint generated by default as identity
        primary key,
    updated_at  timestamp(6),
    updated_by  bigint,
    user_id     bigint       not null
        constraint fkt20rh8x4u8wsq39dmkuttku0p
            references users,
    action      varchar(255) not null,
    entity_name varchar(255) not null
);


create table contacts
(
    created_at   timestamp(6) not null,
    created_by   bigint,
    id           bigint generated by default as identity
        primary key,
    updated_at   timestamp(6),
    updated_by   bigint,
    user_id      bigint       not null
        constraint fkna8bddygr3l3kq1imghgcskt8
            references users,
    company_name varchar(255),
    job_title    varchar(255),
    phone_number varchar(255)
);

create table leads
(
    estimated_value       numeric(15, 2),
    expected_close_date   date,
    follow_up_date        date,
    assigned_sales_rep_id bigint
        constraint fkda5sdv964q191luop31b54lpc
            references users,
    contact_id            bigint       not null
        constraint fknxcfumqfv6xg4it6igem4mki2
            references contacts,
    created_at            timestamp(6) not null,
    created_by            bigint,
    id                    bigint generated by default as identity
        primary key,
    last_activity_date    timestamp(6),
    source_id             bigint       not null
        constraint fk5q2k3ehl603xllc15kpx1mcjy
            references lead_sources,
    updated_at            timestamp(6),
    updated_by            bigint,
    status                varchar(255) not null
        constraint leads_status_check
            check ((status)::text = ANY
                   ((ARRAY ['NEW'::character varying, 'CONTACTED'::character varying, 'QUALIFIED'::character varying, 'PROPOSAL_SENT'::character varying, 'NEGOTIATION'::character varying, 'WON'::character varying, 'LOST'::character varying])::text[]))
);


create table activities
(
    activity_date_time timestamp(6) not null,
    activity_type_id   bigint
        constraint fk9y4tob28y3dslhftgbcb22d94
            references activity_types,
    contact_id         bigint
        constraint fkmdpx4pw34wl4uv1pnuiqfapgv
            references contacts,
    created_at         timestamp(6) not null,
    created_by         bigint,
    id                 bigint generated by default as identity
        primary key,
    lead_id            bigint
        constraint fkf7dwdqdh5opaejcemm2r16t0m
            references leads,
    updated_at         timestamp(6),
    updated_by         bigint,
    user_id            bigint       not null
        constraint fkq6cjukylkgxdjkm9npk9va2f2
            references users,
    description        varchar(255),
    status             varchar(255) not null
        constraint activities_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PLANNED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying])::text[])),
    subject            varchar(255) not null
);


create table report_export_logs
(
    created_at  timestamp(6) not null,
    created_by  bigint,
    exported_at timestamp(6),
    id          bigint generated by default as identity
        primary key,
    updated_at  timestamp(6),
    updated_by  bigint,
    user_id     bigint
        constraint fkdocwirywgfcpgsptr6v5r85tx
            references users,
    format      varchar(255)
        constraint report_export_logs_format_check
            check ((format)::text = ANY ((ARRAY ['PDF'::character varying, 'EXCEL'::character varying, 'CSV'::character varying])::text[])),
    report_name varchar(255)
);
